import warnings
warnings.filterwarnings("ignore")

import numpy as np
import scanpy as sc
import torch
import torch.nn.functional as F
from sklearn.neighbors import NearestNeighbors, kneighbors_graph
from scipy.sparse.csgraph import shortest_path


def umap_cost(
    rna,
    key_added: str = "UMAP4Distance",
    n_components: int = 2,
    l2_normalize: bool = True,
    store_in_obsp: bool = True,
    obsp_key: str = "cost_matrix",
    dtype: torch.dtype = torch.float32,
):
    """
    Calculate pairwise distances (cost matrix) based on UMAP embeddings of RNA expression matrix.

    Args:
        rna: AnnData object containing RNA expression matrix in rna.X
        key_added: Key name to save UMAP embeddings to rna.obsm
        n_components: UMAP dimensions
        l2_normalize: Whether to L2 normalize UMAP row vectors
        store_in_obsp: Whether to store distance matrix in rna.obsp
        obsp_key: Key name for distance matrix in rna.obsp
        dtype: torch dtype used for calculation

    Returns:
        torch.Tensor Pairwise distance matrix of shape (n_cells, n_cells)
    """
    # Neighbors and UMAP embedding
    sc.pp.neighbors(rna)
    sc.tl.umap(rna, key_added=key_added, n_components=n_components)

    # Extract embedding
    embedding = rna.obsm[key_added]
    if not isinstance(embedding, np.ndarray):
        embedding = np.asarray(embedding)

    # Optional L2 normalization (row-wise)
    if l2_normalize:
        tensor_emb = torch.from_numpy(embedding).to(dtype)
        norms = torch.linalg.norm(tensor_emb, dim=1).reshape(-1, 1)
        # Avoid division by zero
        norms = torch.where(norms == 0, torch.ones_like(norms), norms)
        tensor_emb = tensor_emb / norms
    else:
        tensor_emb = torch.from_numpy(embedding).to(dtype)

    # Pairwise distance (Euclidean distance)
    cost_matrix = torch.cdist(tensor_emb, tensor_emb)

    if store_in_obsp:
        # Consistent with existing code, store torch.Tensor; change to cost_matrix.cpu().numpy() if numpy is needed
        rna.obsp[obsp_key] = cost_matrix

    return cost_matrix



def cosine_distance_tensor(X, Y):
    X = torch.from_numpy(X).float() if not isinstance(X, torch.Tensor) else X.float()
    Y = torch.from_numpy(Y).float() if not isinstance(Y, torch.Tensor) else Y.float()
    X_norm = F.normalize(X, p=2, dim=1)
    Y_norm = F.normalize(Y, p=2, dim=1)
    return 1 - torch.mm(X_norm, Y_norm.T)


def knn_cosine_distance(
    adata,
    obsm_key: str = "RNA_pca_l2_norm",
    n_neighbors: int = 20,
    fill_value: float = 1.0,
):
    """
    Calculate sparse distance matrix using KNN + Cosine metric based on an embedding in AnnData (obsm[obsm_key]).
    Non-neighbor positions are filled with fill_value (default 1.0), diagonal is 0.

    Args:
        adata: AnnData object
        obsm_key: Embedding key name (e.g., 'RNA_pca_l2_norm')
        n_neighbors: Number of neighbors k in KNN
        fill_value: Default fill value for non-neighbors (upper bound of cosine distance is 1)

    Returns:
        np.ndarray, shape (n_cells, n_cells)
    """
    X = adata.obsm[obsm_key]
    if not isinstance(X, np.ndarray):
        X = np.asarray(X)

    nbrs = NearestNeighbors(n_neighbors=n_neighbors, algorithm='auto', metric='cosine').fit(X)
    distances, indices = nbrs.kneighbors(X)

    n_spots = X.shape[0]
    dist_mat = np.full((n_spots, n_spots), fill_value, dtype=np.float32)
    for i in range(n_spots):
        for j in range(indices.shape[1]):
            neighbor_idx = indices[i, j]
            dist = distances[i, j]
            dist_mat[i, neighbor_idx] = dist

    np.fill_diagonal(dist_mat, 0.0)
    return dist_mat


def compute_knn_normalized_laplacian(spatial_coords, n_neighbors: int = 5, sigma: float = 1.0):
    """
    Construct Gaussian kernel graph (generated by Euclidean distance) based on spatial coordinates and calculate normalized Laplacian matrix.

    Args:
        spatial_coords: Spatial coordinate array, shape (n_samples, 2) or (n_samples, d)
        n_neighbors: Reserved parameter (can be used if changing to KNN sparse graph), currently unused
        sigma: Gaussian kernel bandwidth

    Returns:
        torch.Tensor, normalized Laplacian matrix (float32)
    """
    from scipy.sparse import csgraph
    from scipy.spatial.distance import cdist

    if isinstance(spatial_coords, torch.Tensor):
        spatial_coords = spatial_coords.numpy()

    dist_matrix = cdist(spatial_coords, spatial_coords, metric='euclidean')
    adjacency_matrix = np.exp(-dist_matrix ** 2 / (2 * sigma ** 2))
    np.fill_diagonal(adjacency_matrix, 0)

    L_scipy = csgraph.laplacian(adjacency_matrix, normed=True)
    L_torch = torch.tensor(L_scipy, dtype=torch.float32)
    return L_torch


def compute_geodesic_distance(X, k=30, metric='cosine'):
    knn_graph = kneighbors_graph(X, n_neighbors=k, mode='distance', metric=metric, include_self=False)
    geo_dist = shortest_path(csgraph=knn_graph, directed=False)
    if np.isinf(geo_dist).any():
        finite_vals = geo_dist[np.isfinite(geo_dist)]
        max_val = finite_vals.max() if len(finite_vals) > 0 else 1.0
        geo_dist[np.isinf(geo_dist)] = max_val * 1.5
    return geo_dist


def compute_spatial_geodesic(coords, features, k_phys=10, metric='cosine'):
    """
    Construct a physically constrained graph, but edge weights are determined by expression features, then calculate geodesic distance.
    Modification: Also return affinity matrix for smoothing.
    """
    from sklearn.neighbors import NearestNeighbors
    from scipy.sparse import csr_matrix
    from scipy.sparse.csgraph import shortest_path
    
    n_samples = features.shape[0]

    # 1. Physical space neighbor construction (define which points can be connected)
    # Set k_phys slightly larger (e.g., 10-15) to ensure the graph is connected and avoid disconnected components due to individual points
    nbrs_phys = NearestNeighbors(n_neighbors=k_phys, metric='euclidean').fit(coords)
    phys_dists, phys_indices = nbrs_phys.kneighbors(coords)

    # 2. Construct edge weights for sparse graph (determined by feature similarity)
    # We traverse physical neighbors and calculate their distance in feature space
    row = []
    col = []
    data_dist = []
    data_aff = []

    # Normalize features for distance calculation
    if metric == 'cosine':
        # Manual L2 normalization for easier dot product calculation
        norms = np.linalg.norm(features, axis=1, keepdims=True)
        # Avoid division by zero
        norms[norms == 0] = 1e-10
        features_norm = features / norms

    for i in range(n_samples):
        # Get physical neighbor indices for the i-th point (skip self, 0 is usually self)
        neighbors = phys_indices[i, 1:]
        
        if metric == 'cosine':
            # Cosine Dist = 1 - (A . B)
            # Distance range is [0, 2]
            # More similar means smaller distance
            dists = 1 - np.dot(features_norm[neighbors], features_norm[i])
            # Fix possible negative value precision errors
            dists = np.maximum(dists, 0)
            
            # Affinity: exp(-dist)
            affs = np.exp(-dists)
        else:
            # Euclidean
            dists = np.linalg.norm(features[neighbors] - features[i], axis=1)
            
            # Gaussian Kernel
            # Reduce sigma (x0.5) to make affinity "sharper", reducing SSIM drop caused by oversmoothing
            sigma = np.mean(dists) * 0.5 + 1e-10
            affs = np.exp(-dists**2 / (2 * sigma**2))

        # Key point: We only establish edges if physically adjacent, edge length is expression difference
        row.extend([i] * len(neighbors))
        col.extend(neighbors)
        data_dist.extend(dists)
        data_aff.extend(affs)

    # 3. Construct sparse adjacency matrix (Distance) - for Geodesic calculation
    adj_dist = csr_matrix((data_dist, (row, col)), shape=(n_samples, n_samples))
    adj_dist = adj_dist + adj_dist.T
    
    # 4. Construct sparse adjacency matrix (Affinity) - for post-processing smoothing
    adj_aff = csr_matrix((data_aff, (row, col)), shape=(n_samples, n_samples))
    adj_aff = adj_aff + adj_aff.T
    
    # 5. Calculate All-Pairs Shortest Path (Geodesic Distance)
    # This calculates "physical travel distance considering tissue boundaries"
    geo_matrix = shortest_path(adj_dist, directed=False)

    # Handle inf values caused by disconnected graph
    if np.isinf(geo_matrix).any():
        finite_vals = geo_matrix[np.isfinite(geo_matrix)]
        max_val = finite_vals.max() if len(finite_vals) > 0 else 1.0
        geo_matrix[np.isinf(geo_matrix)] = max_val * 1.5

    return geo_matrix, adj_aff



def graph_smooth_results(features, adj_matrix, alpha=0.5, n_iter=2):
    """
    Smooth prediction results using Random Walk
    features: (n_spots, n_genes)
    adj_matrix: Sparse adjacency matrix (W)
    alpha: Propagation probability (0~1), larger means smoother
    """
    from scipy.sparse import diags
    
    # Normalize adjacency matrix P = D^-1 * A
    degrees = np.array(adj_matrix.sum(axis=1)).flatten()
    degrees[degrees == 0] = 1  # Avoid division by zero
    D_inv = diags(1.0 / degrees)
    P = D_inv.dot(adj_matrix)
    
    # Iterative smoothing: F_{t+1} = (1-alpha)F_0 + alpha * P * F_t
    F = features.copy()
    F0 = features.copy()
    
    for _ in range(n_iter):
        F = (1 - alpha) * F0 + alpha * P.dot(F)
        
    return F
